module.exports = {
  mode: "jit",
  content: ["./src/**/*.{html,js,ts,tsx}", "./src/**/**/*.{html,js,ts,tsx}"],
  plugins: [require("daisyui")],
  daisyui: {
    styled: true,
    themes: [
      {
        dark: {
          primary: "#FF5400",
          "primary-focus": "#E04B00",
          "primary-content": "#ffffff",
          secondary: "#570df8",
          "secondary-focus": "#4506cb",
          "secondary-content": "#ffffff",
          accent: "#E0007F",
          "accent-focus": "#9E0059",
          "accent-content": "#ffffff",
          neutral: "#3d4451",
          "neutral-focus": "#2a2e37",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#d1d5db",
          "base-content": "#1f2937",
          info: "#2094f3",
          success: "#009485",
          warning: "#FFBD00",
          error: "#FF0054",
        },
        light: {
          primary: "#FF5400",
          "primary-focus": "#E04B00",
          "primary-content": "#ffffff",
          secondary: "#570df8",
          "secondary-focus": "#4506cb",
          "secondary-content": "#ffffff",
          accent: "#E0007F",
          "accent-focus": "#9E0059",
          "accent-content": "#ffffff",
          neutral: "#3d4451",
          "neutral-focus": "#2a2e37",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#d1d5db",
          "base-content": "#1f2937",
          info: "#2094f3",
          success: "#009485",
          warning: "#FFBD00",
          error: "#FF0054",
        },
      },
    ],
  },
};
